import type { InquiryRow, DashboardStats } from "./types";

// Supabaseの環境変数が未設定の場合に使うフィクスチャデータ。
// README/スクリーンショット用、および「git clone直後にすぐ動作を見たい」
// 訪問者のためのデモモードとして機能する。
export const DEMO_INQUIRIES: InquiryRow[] = [
  {
    id: "demo-1",
    channel: "line",
    external_id: "demo-line-1",
    sender: "田中様",
    raw_content: "先週入居したばかりですが、エアコンが全く効かず困っています。至急対応してもらえますか。",
    category: "クレーム",
    confidence: 0.94,
    classification_reason: "設備故障・至急対応の要求を検出",
    is_urgent: true,
    status: "notified",
    retry_count: 0,
    last_error: null,
    next_retry_at: null,
    created_at: new Date(Date.now() - 2 * 60_000).toISOString(),
    classified_at: new Date(Date.now() - 2 * 60_000).toISOString(),
    notified_at: new Date(Date.now() - 2 * 60_000 + 8_000).toISOString(),
  },
  {
    id: "demo-2",
    channel: "gmail",
    external_id: "demo-gmail-1",
    sender: "suzuki@example.com",
    raw_content: "2LDKの賃貸物件を探しています。駅から徒歩10分以内で予算8万円くらいです。",
    category: "賃貸",
    confidence: 0.98,
    classification_reason: "賃貸物件の条件相談と判断",
    is_urgent: false,
    status: "notified",
    retry_count: 0,
    last_error: null,
    next_retry_at: null,
    created_at: new Date(Date.now() - 6 * 60_000).toISOString(),
    classified_at: new Date(Date.now() - 5 * 60_000).toISOString(),
    notified_at: new Date(Date.now() - 5 * 60_000).toISOString(),
  },
  {
    id: "demo-3",
    channel: "gmail",
    external_id: "demo-gmail-2",
    sender: "yamamoto@example.com",
    raw_content: "所有しているマンションの売却を検討しています。査定をお願いできますか。",
    category: "売買",
    confidence: 0.89,
    classification_reason: "物件売却の査定相談と判断",
    is_urgent: false,
    status: "notified",
    retry_count: 0,
    last_error: null,
    next_retry_at: null,
    created_at: new Date(Date.now() - 12 * 60_000).toISOString(),
    classified_at: new Date(Date.now() - 11 * 60_000).toISOString(),
    notified_at: new Date(Date.now() - 11 * 60_000).toISOString(),
  },
  {
    id: "demo-4",
    channel: "line",
    external_id: "demo-line-2",
    sender: "佐藤様",
    raw_content: "来週の土曜日に、駅前の新築マンションを内見したいです。",
    category: "内見",
    confidence: 0.96,
    classification_reason: "内見日程の調整依頼と判断",
    is_urgent: false,
    status: "classified",
    retry_count: 0,
    last_error: null,
    next_retry_at: null,
    created_at: new Date(Date.now() - 3 * 60_000).toISOString(),
    classified_at: new Date(Date.now() - 3 * 60_000).toISOString(),
    notified_at: null,
  },
  {
    id: "demo-5",
    channel: "gmail",
    external_id: "demo-gmail-3",
    sender: "kobayashi@example.com",
    raw_content: "水漏れが発生していて、床が水浸しです。管理会社の対応が遅く、非常に困っています。",
    category: "クレーム",
    confidence: 0.91,
    classification_reason: "設備トラブル・強い不満を検出",
    is_urgent: true,
    status: "failed",
    retry_count: 1,
    last_error: "Slack API timeout",
    next_retry_at: new Date(Date.now() + 30_000).toISOString(),
    created_at: new Date(Date.now() - 1 * 60_000).toISOString(),
    classified_at: new Date(Date.now() - 1 * 60_000).toISOString(),
    notified_at: null,
  },
  {
    id: "demo-6",
    channel: "line",
    external_id: "demo-line-3",
    sender: "高橋様",
    raw_content: "ペット可の賃貸マンションを探しています。猫を2匹飼っています。",
    category: null,
    confidence: null,
    classification_reason: null,
    is_urgent: false,
    status: "pending",
    retry_count: 0,
    last_error: null,
    next_retry_at: null,
    created_at: new Date(Date.now() - 30_000).toISOString(),
    classified_at: null,
    notified_at: null,
  },
];

export const DEMO_STATS: DashboardStats = {
  total_count: 758,
  urgent_count: 12,
  failed_count: 1,
  notified_count: 741,
  success_rate_pct: 99.6,
};

export function isDemoMode(): boolean {
  return !process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY;
}

export const DEMO_LOGS = [
  {
    id: "log-1",
    inquiry_id: "demo-1",
    target: "line" as const,
    success: true,
    error_message: null,
    created_at: new Date(Date.now() - 2 * 60_000).toISOString(),
    inquiry_queue: { raw_content: DEMO_INQUIRIES[0].raw_content, category: "クレーム" },
  },
  {
    id: "log-2",
    inquiry_id: "demo-1",
    target: "slack" as const,
    success: true,
    error_message: null,
    created_at: new Date(Date.now() - 2 * 60_000).toISOString(),
    inquiry_queue: { raw_content: DEMO_INQUIRIES[0].raw_content, category: "クレーム" },
  },
  {
    id: "log-3",
    inquiry_id: "demo-2",
    target: "slack" as const,
    success: true,
    error_message: null,
    created_at: new Date(Date.now() - 5 * 60_000).toISOString(),
    inquiry_queue: { raw_content: DEMO_INQUIRIES[1].raw_content, category: "賃貸" },
  },
  {
    id: "log-4",
    inquiry_id: "demo-5",
    target: "slack" as const,
    success: false,
    error_message: "Slack API error: timeout after 3000ms",
    created_at: new Date(Date.now() - 1 * 60_000).toISOString(),
    inquiry_queue: { raw_content: DEMO_INQUIRIES[4].raw_content, category: "クレーム" },
  },
];
